#!/bin/sh
#
#Check build variants before push.

echo "CHECKING DEBUG built ..."
#./gradlew :app:lintDebug
./gradlew :app:compileDebugSources
debugStatus=$?

if [ $debugStatus -ne 0 ]
then
  cat <<\EOF
Error: compileDebugSources BUILT FAILURE, git commit aborted.
EOF
  exit 1
  
else
	echo "CHECKING DEBUG built ..."
	#./gradlew :app:lintRelease
	./gradlew :app:compileReleaseSources
	realeseStatus=$?
	
	if [ $realeseStatus -ne 0 ]
	then
		cat <<\EOF
Error: compileReleaseSources BUILT FAILURE, git commit aborted.
EOF
		exit 1
	fi
  
fi

